apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-metadata-name-payment
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: springio/gs-spring-boot-docker
        ports:
        - containerPort: 8080

#create deployment process
# kubectl create -f deployment.yml --save-config
#apply changes to deployment process
# kubectl apply -f deployment.yml
#list all deployments
# kubectl get deployments
# get deployment by label
# kubectl get deployment -l app=nikolaLabelApp
#scale the deployment pods to 5
# kubectl scale deployment "deployment-name" --replicas=5